// Generated by Wrangler on Mon May 27 2024 19:20:31 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	kv: KVNamespace;
	redirect: string;
	analytics: AnalyticsEngineDataset;
}
