#:schema node_modules/wrangler/config-schema.json
name = "shortner"
main = "src/index.ts"
compatibility_date = "2024-05-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "kv", id = "c869beabc3534aadb787c0d8b3661e1d" }
]

[[analytics_engine_datasets]]
binding = "analytics"
