#:schema node_modules/wrangler/config-schema.json
name = "shortner"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "kv", id = "663cd5c74988404dafbf67e1e06b21e8" }
]

[[analytics_engine_datasets]]
binding = "analytics"
dataset = "shortner"

[observability]
enabled = true